name: UX BPMN

on: [push, pull_request]

jobs:
  static-test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: php-cs-fixer, phpstan
      - name: Install vendors
        run: composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
      - name: php-cs-fixer
        run: php-cs-fixer fix --dry-run --diff
      - name: phpstan
        run: phpstan

  static-test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          cd Resources/assets
          yarn
          yarn lint:check

  tests-php74-low-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpunit
      - name: PHP 7.4 and lowest
        run: |
          composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
          phpunit

  tests-php80-low-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpunit
      - name: PHP 8.0 and lowest
        run: |
          composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
          phpunit

  tests-php80-high-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpunit
      - name: PHP 8.0 and highest
        run: |
          composer update --prefer-dist --no-interaction --no-ansi --no-progress
          phpunit